spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/itat_emp
    username: root
    password: Cloud12345
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


